package cz.radovanmoncek.client.ship.tables;// automatically generated by the FlatBuffers compiler, do not modify

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ChatMessage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static ChatMessage getRootAsChatMessage(ByteBuffer _bb) { return getRootAsChatMessage(_bb, new ChatMessage()); }
  public static ChatMessage getRootAsChatMessage(ByteBuffer _bb, ChatMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ChatMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String authorPlayerNickname() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer authorPlayerNicknameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer authorPlayerNicknameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String messageContent() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageContentAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer messageContentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createChatMessage(FlatBufferBuilder builder,
      int authorPlayerNicknameOffset,
      int messageContentOffset) {
    builder.startTable(2);
    ChatMessage.addMessageContent(builder, messageContentOffset);
    ChatMessage.addAuthorPlayerNickname(builder, authorPlayerNicknameOffset);
    return ChatMessage.endChatMessage(builder);
  }

  public static void startChatMessage(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addAuthorPlayerNickname(FlatBufferBuilder builder, int authorPlayerNicknameOffset) { builder.addOffset(0, authorPlayerNicknameOffset, 0); }
  public static void addMessageContent(FlatBufferBuilder builder, int messageContentOffset) { builder.addOffset(1, messageContentOffset, 0); }
  public static int endChatMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ChatMessage get(int j) { return get(new ChatMessage(), j); }
    public ChatMessage get(ChatMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

