package cz.radovanmoncek.client.ship.tables;// automatically generated by the FlatBuffers compiler, do not modify

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 *Request from players
 */
@SuppressWarnings("unused")
public final class GameStateRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static GameStateRequest getRootAsGameStateRequest(ByteBuffer _bb) { return getRootAsGameStateRequest(_bb, new GameStateRequest()); }
  public static GameStateRequest getRootAsGameStateRequest(ByteBuffer _bb, GameStateRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GameStateRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int x() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int y() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int rotationAngle() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public byte gameStatusRequest() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String gameCode() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer gameCodeAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer gameCodeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String name() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }

  public static int createGameStateRequest(FlatBufferBuilder builder,
      int x,
      int y,
      int rotationAngle,
      byte gameStatusRequest,
      int gameCodeOffset,
      int nameOffset) {
    builder.startTable(6);
    GameStateRequest.addName(builder, nameOffset);
    GameStateRequest.addGameCode(builder, gameCodeOffset);
    GameStateRequest.addRotationAngle(builder, rotationAngle);
    GameStateRequest.addY(builder, y);
    GameStateRequest.addX(builder, x);
    GameStateRequest.addGameStatusRequest(builder, gameStatusRequest);
    return GameStateRequest.endGameStateRequest(builder);
  }

  public static void startGameStateRequest(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addX(FlatBufferBuilder builder, int x) { builder.addInt(0, x, 0); }
  public static void addY(FlatBufferBuilder builder, int y) { builder.addInt(1, y, 0); }
  public static void addRotationAngle(FlatBufferBuilder builder, int rotationAngle) { builder.addInt(2, rotationAngle, 0); }
  public static void addGameStatusRequest(FlatBufferBuilder builder, byte gameStatusRequest) { builder.addByte(3, gameStatusRequest, 0); }
  public static void addGameCode(FlatBufferBuilder builder, int gameCodeOffset) { builder.addOffset(4, gameCodeOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(5, nameOffset, 0); }
  public static int endGameStateRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GameStateRequest get(int j) { return get(new GameStateRequest(), j); }
    public GameStateRequest get(GameStateRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

