package cz.radovanmoncek.client.ship.tables;// automatically generated by the FlatBuffers compiler, do not modify

@SuppressWarnings("unused")
public final class GameStatus {
  private GameStatus() { }
  public static final byte START_SESSION = 0;
  public static final byte STOP_SESSION = 1;
  public static final byte JOIN_SESSION = 2;
  public static final byte STATE_CHANGE = 3;
  public static final byte INVALID_STATE = 4;

  public static final String[] names = { "START_SESSION", "STOP_SESSION", "JOIN_SESSION", "STATE_CHANGE", "INVALID_STATE", };

  public static String name(int e) { return names[e]; }
}

